"""modified the review column

Revision ID: 48279efcf871
Revises: a363419513cf
Create Date: 2021-05-05 11:54:23.206621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48279efcf871'
down_revision = 'a363419513cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviews', 'thoughts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('thoughts', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
